/* ------------------------------------------------------------------ *
 *  PROJECT: GLOBE  —  penguin dataset
 *  Facts: IUCN Red List + species literature. Playful fields
 *  (pet index, arch-nemesis, field note) are clearly flavour.
 *  Photos: live from Wikimedia Commons (every URL verified to
 *  resolve to image/jpeg before shipping). Colours are NOT applied
 *  to photos — only to the site chrome.
 * ------------------------------------------------------------------ */

const WC = "https://commons.wikimedia.org/wiki/Special:FilePath/";
const img = (file) => WC + encodeURIComponent(file) + "?width=900";

// Conservation severity → 0 LC · 1 NT · 2 VU · 3 EN · 4 CR
const PENGUINS = [
  {
    id: "emperor",
    name: "Emperor",
    binomial: "Aptenodytes forsteri",
    photo: img("Aptenodytes forsteri -Snow Hill Island, Antarctica -adults and juvenile-8.jpg"),
    status: "Near Threatened", statusCode: "NT", severity: 1,
    trend: "Decreasing",
    size: "≈ 115 cm tall", weight: "22–45 kg",
    lifespan: "15–20 years",
    diet: "Fish, krill, squid",
    range: "Fast ice around the Antarctic continent",
    petIndex: 1,
    nemesis: "Leopard seal & orca at sea · skua and giant petrel take the chicks",
    fieldNote: "The only animal that breeds through the Antarctic winter. The male balances the single egg on his feet under a belly fold for ~65 days, fasting in −40 °C dark while the female feeds at sea.",
    colonies: [
      { name: "Atka Bay", lat: -70.6, lon: -8.2 },
      { name: "Cape Washington, Ross Sea", lat: -74.6, lon: 165.4 },
      { name: "Snow Hill Island", lat: -64.5, lon: -57.4 },
    ],
  },
  {
    id: "king",
    name: "King",
    binomial: "Aptenodytes patagonicus",
    photo: img("SGI-2016-South Georgia (Fortuna Bay)–King penguin (Aptenodytes patagonicus) 04.jpg"),
    status: "Least Concern", statusCode: "LC", severity: 0,
    trend: "Stable",
    size: "≈ 90 cm tall", weight: "11–16 kg",
    lifespan: "≈ 26 years",
    diet: "Lanternfish & squid",
    range: "Sub-Antarctic islands — South Georgia, Crozet, Kerguelen, Macquarie",
    petIndex: 2,
    nemesis: "Leopard seal & orca · skua and giant petrel near the colony",
    fieldNote: "Has the longest breeding cycle of any bird — 14–16 months per chick. The fluffy brown chicks were once mistaken for a separate species and called 'woolly penguins'.",
    colonies: [
      { name: "South Georgia", lat: -54.0, lon: -37.0 },
      { name: "Crozet Islands", lat: -46.4, lon: 51.8 },
      { name: "Macquarie Island", lat: -54.6, lon: 158.9 },
    ],
  },
  {
    id: "gentoo",
    name: "Gentoo",
    binomial: "Pygoscelis papua",
    photo: img("Brown Bluff-2016-Tabarin Peninsula–Gentoo penguin (Pygoscelis papua) 03.jpg"),
    status: "Least Concern", statusCode: "LC", severity: 0,
    trend: "Stable / increasing",
    size: "75–90 cm tall", weight: "5–8.5 kg",
    lifespan: "15–20 years",
    diet: "Krill, fish, squid",
    range: "Antarctic Peninsula, Falklands, South Georgia, Kerguelen",
    petIndex: 3,
    nemesis: "Leopard seal, sea lion & orca · skua robs the eggs",
    fieldNote: "The fastest underwater bird on Earth — bursts to ~36 km/h. Courtship is a 'pebble proposal': the male presents the smoothest stone he can find and hopes she keeps it.",
    colonies: [
      { name: "Falkland Islands", lat: -51.7, lon: -59.2 },
      { name: "Antarctic Peninsula", lat: -64.8, lon: -62.7 },
      { name: "South Georgia", lat: -54.3, lon: -36.5 },
    ],
  },
  {
    id: "adelie",
    name: "Adélie",
    binomial: "Pygoscelis adeliae",
    photo: img("Hope Bay-2016-Trinity Peninsula–Adélie penguin (Pygoscelis adeliae) 04.jpg"),
    status: "Least Concern", statusCode: "LC", severity: 0,
    trend: "Increasing",
    size: "≈ 70 cm tall", weight: "3.6–6 kg",
    lifespan: "10–20 years",
    diet: "Krill, fish, amphipods",
    range: "The entire Antarctic coastline",
    petIndex: 2,
    nemesis: "Leopard seal & orca · skua takes eggs and chicks",
    fieldNote: "Builds its nest from pebbles and will happily steal them from a neighbour the moment its back is turned. Named after Adèle, wife of the French explorer Dumont d'Urville.",
    colonies: [
      { name: "Ross Island", lat: -77.5, lon: 166.2 },
      { name: "Hope Bay", lat: -63.4, lon: -57.0 },
      { name: "Cape Adare", lat: -71.3, lon: 170.2 },
    ],
  },
  {
    id: "chinstrap",
    name: "Chinstrap",
    binomial: "Pygoscelis antarcticus",
    photo: img("South Shetland-2016-Deception Island–Chinstrap penguin (Pygoscelis antarctica) 04.jpg"),
    status: "Least Concern", statusCode: "LC", severity: 0,
    trend: "Decreasing",
    size: "≈ 70 cm tall", weight: "3–5 kg",
    lifespan: "15–20 years",
    diet: "Almost entirely krill",
    range: "South Sandwich & South Shetland Islands, Antarctic Peninsula",
    petIndex: 3,
    nemesis: "Leopard seal & orca · skua and sheathbill raid nests",
    fieldNote: "Named for the thin black strap under the chin. Around 1.5 million pairs nest on Zavodovski — an active volcano whose heat keeps the breeding slopes clear of ice.",
    colonies: [
      { name: "South Sandwich Islands", lat: -57.1, lon: -26.6 },
      { name: "Deception Island", lat: -63.0, lon: -60.6 },
      { name: "Zavodovski Island", lat: -56.3, lon: -27.6 },
    ],
  },
  {
    id: "little",
    name: "Little Blue",
    binomial: "Eudyptula minor",
    photo: img("Eudyptula minor Bruny 1.jpg"),
    status: "Least Concern", statusCode: "LC", severity: 0,
    trend: "Stable (declining locally)",
    size: "≈ 33 cm tall — the smallest", weight: "≈ 1 kg",
    lifespan: "≈ 6 years wild (to 25 in care)",
    diet: "Small fish, squid, krill",
    range: "Southern coasts of Australia & New Zealand",
    petIndex: 4,
    nemesis: "Fur seals & sharks at sea · dogs, foxes and cats ashore",
    fieldNote: "Comes ashore only after dark, waddling up the beach in groups called 'rafts'. The nightly Penguin Parade on Phillip Island is the closest you'll get to one — and you still can't keep it.",
    colonies: [
      { name: "Phillip Island", lat: -38.5, lon: 145.2 },
      { name: "Oamaru, NZ", lat: -45.1, lon: 170.97 },
      { name: "Bruny Island", lat: -43.4, lon: 147.3 },
    ],
  },
  {
    id: "galapagos",
    name: "Galápagos",
    binomial: "Spheniscus mendiculus",
    photo: img("Galápagos penguin (Spheniscus mendiculus) male.jpg"),
    status: "Endangered", statusCode: "EN", severity: 3,
    trend: "Decreasing",
    size: "≈ 49 cm tall", weight: "≈ 2.5 kg",
    lifespan: "15–20 years",
    diet: "Small fish — mullet, sardines, anchovies",
    range: "Galápagos Islands — the only penguin found north of the equator",
    petIndex: 2,
    nemesis: "Sharks, sea lions & fur seals at sea · crabs, snakes and introduced cats on land",
    fieldNote: "The only penguin that can stand in the Northern Hemisphere, cooled by the Humboldt Current at the equator. El Niño years collapse its food supply and the population with it.",
    colonies: [
      { name: "Isabela Island", lat: -0.30, lon: -91.10 },
      { name: "Fernandina Island", lat: -0.37, lon: -91.55 },
      { name: "Bartolomé Island", lat: -0.28, lon: -90.55 },
    ],
  },
  {
    id: "african",
    name: "African",
    binomial: "Spheniscus demersus",
    photo: img("African penguin at Boulders Beach 01.jpg"),
    status: "Critically Endangered", statusCode: "CR", severity: 4,
    trend: "Decreasing rapidly",
    size: "60–70 cm tall", weight: "2.2–3.5 kg",
    lifespan: "10–27 years",
    diet: "Anchovies, sardines, small fish",
    range: "Coast of South Africa & Namibia",
    petIndex: 3,
    nemesis: "Cape fur seals & sharks at sea · kelp gulls and mongoose take eggs ashore",
    fieldNote: "Also called the 'jackass penguin' for its donkey-like bray. Its wild population has fallen roughly 97% in a century — uplisted by the IUCN to Critically Endangered in 2024.",
    colonies: [
      { name: "Boulders Beach", lat: -34.2, lon: 18.5 },
      { name: "Dyer Island", lat: -34.7, lon: 19.4 },
      { name: "Mercury Island, Namibia", lat: -25.7, lon: 14.8 },
    ],
  },
  {
    id: "magellanic",
    name: "Magellanic",
    binomial: "Spheniscus magellanicus",
    photo: img("MagellanicPenguin.jpg"),
    status: "Least Concern", statusCode: "LC", severity: 0,
    trend: "Increasing",
    size: "≈ 70 cm tall", weight: "2.7–6.5 kg",
    lifespan: "≈ 25 years",
    diet: "Small fish, squid, krill",
    range: "Coasts of Argentina, Chile & the Falklands; winters north to Brazil",
    petIndex: 3,
    nemesis: "Sea lions, orcas & fur seals at sea · gulls, skuas and foxes take the eggs",
    fieldNote: "Digs a burrow in the dirt to nest. Punta Tombo in Argentina holds one of the largest colonies on Earth — hundreds of thousands of pairs arriving every spring. Oil spills and shifting fish stocks are the modern threat.",
    colonies: [
      { name: "Punta Tombo", lat: -44.05, lon: -65.2 },
      { name: "Magdalena Island", lat: -52.9, lon: -70.6 },
      { name: "Falkland Islands", lat: -51.7, lon: -59.0 },
    ],
  },
  {
    id: "humboldt",
    name: "Humboldt",
    binomial: "Spheniscus humboldti",
    photo: img("Spheniscus humboldti (54905367722).jpg"),
    status: "Vulnerable", statusCode: "VU", severity: 2,
    trend: "Decreasing",
    size: "56–70 cm tall", weight: "4–5 kg",
    lifespan: "15–20 years",
    diet: "Anchovies, sardines, small schooling fish",
    range: "Pacific coast of Peru & Chile, along the cold Humboldt Current",
    petIndex: 3,
    nemesis: "Sea lions, sharks & fur seals at sea · gulls, foxes and introduced cats/rats raid nests",
    fieldNote: "Burrows into ancient guano deposits to nest — then a century of guano mining stripped the nesting ground away. El Niño years collapse the anchovy shoals it lives on.",
    colonies: [
      { name: "Punta San Juan, Peru", lat: -15.4, lon: -75.2 },
      { name: "Isla Chañaral, Chile", lat: -29.0, lon: -71.6 },
      { name: "Algarrobo, Chile", lat: -33.4, lon: -71.7 },
    ],
  },
  {
    id: "yellow-eyed",
    name: "Yellow-eyed",
    binomial: "Megadyptes antipodes",
    photo: img("Yellow-eyed Penguin MC.jpg"),
    status: "Endangered", statusCode: "EN", severity: 3,
    trend: "Decreasing",
    size: "62–79 cm tall", weight: "5–6 kg",
    lifespan: "≈ 20 years",
    diet: "Fish (blue cod, opalfish) & squid",
    range: "South-east New Zealand, Stewart, Auckland & Campbell Islands",
    petIndex: 2,
    nemesis: "NZ sea lions & sharks at sea · introduced stoats, ferrets, cats and dogs on land",
    fieldNote: "One of the rarest penguins alive. Called 'hoiho' — the noise shouter — in Māori. Unlike almost every other penguin it nests alone in forest and scrub, hidden from the sight of other pairs.",
    colonies: [
      { name: "Otago Peninsula", lat: -45.8, lon: 170.7 },
      { name: "Stewart Island", lat: -47.0, lon: 167.8 },
      { name: "Campbell Island", lat: -52.5, lon: 169.1 },
    ],
  },
  {
    id: "fiordland",
    name: "Fiordland",
    binomial: "Eudyptes pachyrhynchus",
    photo: img("Fiordland Crested Penguin.jpg"),
    status: "Near Threatened", statusCode: "NT", severity: 1,
    trend: "Decreasing",
    size: "55–60 cm tall", weight: "3–4 kg",
    lifespan: "10–20 years",
    diet: "Squid, krill & small fish",
    range: "South-west New Zealand (Fiordland) & Stewart Island",
    petIndex: 2,
    nemesis: "Fur seals, sea lions & sharks at sea · stoats, rats and dogs take eggs and chicks",
    fieldNote: "'Tawaki' — one of the only penguins that breeds in temperate rainforest, nesting under tree roots and in sea caves. Some swim thousands of kilometres into the Southern Ocean to fatten up before moulting.",
    colonies: [
      { name: "Fiordland coast", lat: -45.5, lon: 167.0 },
      { name: "Stewart Island", lat: -47.0, lon: 167.8 },
      { name: "Solander Islands", lat: -46.6, lon: 166.9 },
    ],
  },
  {
    id: "snares",
    name: "Snares",
    binomial: "Eudyptes robustus",
    photo: img("Snares Penguin, Southland, NZ imported from iNaturalist photo 347215306.jpg"),
    status: "Vulnerable", statusCode: "VU", severity: 2,
    trend: "Decreasing",
    size: "≈ 55 cm tall", weight: "2.5–4 kg",
    lifespan: "15–20 years",
    diet: "Krill, squid & small fish",
    range: "Breeds only on the Snares Islands, south of New Zealand",
    petIndex: 2,
    nemesis: "NZ sea lions, fur seals & sharks · skuas and giant petrels take the chicks",
    fieldNote: "The entire world population breeds on one tiny island group — the Snares — and nowhere else. They nest under a tree-daisy forest and commute to the sea down well-worn, muddy 'penguin highways'.",
    colonies: [
      { name: "North East Island, Snares", lat: -48.02, lon: 166.60 },
      { name: "Broughton Island, Snares", lat: -48.05, lon: 166.62 },
      { name: "Western Chain, Snares", lat: -48.07, lon: 166.42 },
    ],
  },
  {
    id: "erect-crested",
    name: "Erect-crested",
    binomial: "Eudyptes sclateri",
    photo: img("Erect-crested penguin (Eudyptes sclateri).jpg"),
    status: "Endangered", statusCode: "EN", severity: 3,
    trend: "Decreasing",
    size: "≈ 60 cm tall", weight: "4–6 kg",
    lifespan: "15–20 years",
    diet: "Krill, squid & small fish",
    range: "Breeds only on the Bounty & Antipodes Islands, NZ subantarctic",
    petIndex: 2,
    nemesis: "Fur seals & sharks at sea · skuas and giant petrels take eggs and chicks",
    fieldNote: "The only penguin whose stiff golden crest can be raised and lowered like a pair of eyebrows. It breeds on just two remote island groups and has lost roughly half its population in recent decades.",
    colonies: [
      { name: "Bounty Islands", lat: -47.75, lon: 179.05 },
      { name: "Antipodes Islands", lat: -49.68, lon: 178.8 },
    ],
  },
  {
    id: "s-rockhopper",
    name: "Southern Rockhopper",
    binomial: "Eudyptes chrysocome",
    photo: img("Rockhopper Penguin on Saunders Island (5586446214).jpg"),
    status: "Vulnerable", statusCode: "VU", severity: 2,
    trend: "Decreasing",
    size: "≈ 52 cm tall", weight: "2–3.4 kg",
    lifespan: "≈ 10 years (to 30)",
    diet: "Krill, squid & small fish",
    range: "Subantarctic islands — Falklands, southern Chile/Argentina, Crozet, Kerguelen, Macquarie",
    petIndex: 3,
    nemesis: "Fur seals, sea lions & orcas · skuas, gulls and giant petrels take the eggs",
    fieldNote: "Doesn't waddle so much as bounce — it hops up steep, slick cliffs with both feet together rather than climbing. Red eyes, spiky yellow brows, and an attitude several sizes too big for its body.",
    colonies: [
      { name: "Falkland Islands", lat: -51.7, lon: -59.0 },
      { name: "Isla de los Estados", lat: -54.8, lon: -64.3 },
      { name: "Campbell Island", lat: -52.5, lon: 169.1 },
    ],
  },
  {
    id: "n-rockhopper",
    name: "Northern Rockhopper",
    binomial: "Eudyptes moseleyi",
    photo: img("Eudyptes moseleyi -Zoologischer Garten Berlin, Germany-8a.jpg"),
    status: "Endangered", statusCode: "EN", severity: 3,
    trend: "Decreasing",
    size: "≈ 55 cm tall", weight: "2.5–3.4 kg",
    lifespan: "≈ 10 years",
    diet: "Krill, squid & small fish",
    range: "Tristan da Cunha & Gough (S Atlantic); Amsterdam & St Paul (Indian Ocean)",
    petIndex: 3,
    nemesis: "Fur seals & sharks at sea · skuas, and introduced mice on Gough, attack chicks",
    fieldNote: "Wears longer, shaggier yellow plumes than its southern cousin. Almost the entire species nests on a handful of remote Atlantic islands — and it has crashed by an estimated 90% over a century.",
    colonies: [
      { name: "Gough Island", lat: -40.3, lon: -9.9 },
      { name: "Tristan da Cunha", lat: -37.1, lon: -12.3 },
      { name: "Amsterdam Island", lat: -37.8, lon: 77.5 },
    ],
  },
  {
    id: "macaroni",
    name: "Macaroni",
    binomial: "Eudyptes chrysolophus",
    photo: img("SGI-2016-South Georgia (Cooper Bay)–Macaroni penguin (Eudyptes chrysolophus) 01.jpg"),
    status: "Vulnerable", statusCode: "VU", severity: 2,
    trend: "Decreasing",
    size: "≈ 70 cm tall", weight: "5–6 kg",
    lifespan: "8–15 years (to 20)",
    diet: "Krill, small fish & squid",
    range: "Subantarctic — South Georgia, South Sandwich, Crozet, Kerguelen, Heard",
    petIndex: 2,
    nemesis: "Leopard seals, fur seals & orcas · skuas and giant petrels take the eggs",
    fieldNote: "Possibly the most numerous penguin on Earth — and still declining. Named by 18th-century sailors after the flamboyant 'macaroni' dandies for its orange crest. Lays two eggs but almost always raises only the second, larger one.",
    colonies: [
      { name: "South Georgia", lat: -54.0, lon: -37.0 },
      { name: "South Sandwich Islands", lat: -57.5, lon: -26.5 },
      { name: "Kerguelen Islands", lat: -49.3, lon: 69.5 },
    ],
  },
  {
    id: "royal",
    name: "Royal",
    binomial: "Eudyptes schlegeli",
    photo: img("RoyalPenguins2.JPG"),
    status: "Near Threatened", statusCode: "NT", severity: 1,
    trend: "Stable",
    size: "≈ 70 cm tall", weight: "3–8 kg",
    lifespan: "15–20 years",
    diet: "Krill, fish & squid",
    range: "Breeds almost entirely on Macquarie Island, between NZ & Antarctica",
    petIndex: 2,
    nemesis: "Fur seals & orcas at sea · skuas and giant petrels take eggs and chicks",
    fieldNote: "Nearly the whole species breeds on a single island — Macquarie. Often considered a white-faced form of the macaroni penguin. Once boiled for oil by the hundreds of thousands; the colonies have slowly recovered.",
    colonies: [
      { name: "Macquarie Island", lat: -54.6, lon: 158.9 },
      { name: "Hurd Point, Macquarie", lat: -54.75, lon: 158.9 },
      { name: "Bishop & Clerk Islets", lat: -55.1, lon: 158.6 },
    ],
  },
];
